### ISSUE TITLE
Does this also work for libraries that contain their types?

### ISSUE THREAD

**Issue by Naxos84** [ui5-community/ui5-ts-shim-showcase#2]
I tried to use "moment" and followed everything you did.

It works during runtime but VsCode complains about the import.

ErrorMessage: Cannot find module 'moment'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?

I did:
`npm i moment -D`

//package.json
```json
"ui5": {
    "dependencies": [
      "ui5-middleware-livereload",
      "moment",
      "lodash"
    ]
  },
```

//ui5.yaml
```
---
specVersion: "2.0"
kind: extension
type: project-shim
metadata:
  name: my.project.thirdparty # this can be your project shim name
shims:
  configurations:
    moment: # name as defined in package.json
      specVersion: "2.0"
      type: module # Use module type
      metadata:
        name: moment
      resources:
        configuration:
          paths:
            "/thirdparty/moment/": "" # location where modules are stored
    lodash: # dependency name as defined in package.json
      specVersion: "2.0"
      type: module # module type
      metadata:
        name: lodash
      resources:
        configuration:
          paths:
            "/thirdparty/lodash/": "" # map root directory of lodash module into projects' thirdparty namespace
```

//Component.ts
```js
sap.ui.loader.config({
  map: {
    "*": {
      moment: "my/project/thirdparty/moment/moment",
      lodash: "my/project/thirdparty/lodash/lodash",
    },
  },
  shim: {
    "my/project/thirdparty/moment/moment": {
      amd: true,
      deps: [],
      exports: "moment",
    },
    "my/project/thirdparty/lodash/lodash": {
      amd: true,
      deps: [],
      exports: "_",
    },
  },
});
```

//MyController.controller.ts
```ts
import Controller from "sap/ui/core/mvc/Controller";
import moment from "moment";
export default class MyController extends Controller {
    onInit() {
        console.log(moment());
    }
}
```

I do think that my `tsconfig.json` might be the problem cause it is working during runtime and only complaining about the import.
